version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  imageserver:
    image: naturalis/imageserver:0.0.1
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 8080:80
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.imageserver.entrypoints=https
      - traefik.http.routers.imageserver.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.imageserver.tls=true
      - traefik.http.routers.imageserver.rule=${SITE_URL:-Host(`images.naturalis.nl`)}
    volumes:
      - ${BASE_PATH:-/data}/www:${WEB_DOCROOT:-/var/www/html}
    networks:
      - default
      - web

  fpm:
    image: naturalis/fpm:0.0.1
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${BASE_PATH:-/data}/www:/data
      - /var/log/imageserver:/var/log/imageserver
    networks:
      - default

  minio:
    image: "minio/minio:RELEASE.2019-10-12T01-39-57Z"
    restart: unless-stopped
    command: "server /data"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-12345}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-12345678}
    logging: *default-logging
    ports:
      - "9000:9000"
    volumes: 
      - "${BASE_PATH:-/data}/ccw:/data"
      - "${BASE_PATH:-/data}/minioconfig:/root/.minio"
    networks:
      - default
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.minio.entrypoints=https
      - traefik.http.routers.minio.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.rule=${MINIO_SITE_URL:-Host(`minio.images.naturalis.nl`)}

  traefik:
    image: traefik:2.0.1
    container_name: traefik
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

networks:
    default:
    web:
        external: true
