version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  imageserver:
    image: naturalis/imageserver:0.0.1
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 8080:80
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.imageserver.entrypoints=https
      - traefik.http.routers.imageserver.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.imageserver.tls=true
      - traefik.http.routers.imageserver.rule=${SITE_URL:-Host(`images.naturalis.nl`)}
    volumes:
      - ${BASE_PATH:-/data}/www:${WEB_DOCROOT:-/var/www/html}
    networks:
      - default
      - web

  fpm:
    image: naturalis/fpm:0.0.1
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ${BASE_PATH:-/data}/www:/data
      - /var/log/imageserver:/var/log/imageserver
    networks:
      - default

  traefik:
    image: traefik:2.0.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

networks:
    default:
    web:
        external: true
